name: Build and Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      # Host app
      - name: Install host dependencies
        working-directory: ./host
        run: npm ci

      - name: Build host
        working-directory: ./host
        run: npm run build

      # Remote app
      - name: Install remote dependencies
        working-directory: ./remote
        run: npm ci

      - name: Build remote
        working-directory: ./remote
        run: npm run build

      # Server app
      - name: Install server dependencies
        working-directory: ./server
        run: npm ci

      - name: Build server
        working-directory: ./server
        run: npm run build

      - name: Create release artifacts
        run: |
          tar -czf host-dist.tar.gz -C host/dist .
          tar -czf remote-dist.tar.gz -C remote/dist .
          tar -czf server-dist.tar.gz -C server/dist .

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            host-dist.tar.gz
            remote-dist.tar.gz
            server-dist.tar.gz
          name: Release ${{ github.ref_name }}
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 